version = 0.1
[default.deploy.parameters]
stack_name = "ContactCenterApp"
resolve_s3 = true
s3_prefix = "ContactCenterApp"
region = "us-west-2"
profile = "Capstone"
capabilities = "CAPABILITY_IAM"
image_repositories = []
